In [7]:
%reset -f -s

In [ ]:
import numpy as np


![示例图片](./GridWorld.png)

In [2]:
nEpoch = 150
Gamma= 0.9
# 状态价值。初始记录在第0行。
StateValue = np.zeros((nEpoch+1, 2))

# 动作即时奖励
ActionReward = np.array([[-1, 0 , 1],
                         [-1, 0 , -1]])

# 每个状态下采取各种行动的概率，即策略
Prob_Action = np.array([ [1/3, 1/3, 1/3],
                         [1/3, 1/3, 1/3]])
# print(StateValue.T)

In [3]:
# S1和S2状态下，动作转移到状态的概率
Prob_State_by_Action = np.array([ [ [1, 1, 0], [0, 0, 1] ],
                                  [ [1, 0, 0], [0, 1, 1] ] ])
# 说明：[1, 1, 0]代表a1动作一定去s1状态，a2动作一定去s1状态，a3动作一定不去s1状态。
### print("{0}\t{1}".format(Prob_State_by_Action.shape, Prob_State_by_Action[0].shape))

### 1. 按解析解方式求解状态价值

$ V_{\pi} = R_{\pi} + \gamma  P_{\pi} V_{\pi} ，\quad V_{\pi}是策略\pi下的状态价值向量，R_{\pi}是策略\pi下的即时奖励向量，\gamma是折扣因子，P_{\pi}是状态转移矩阵。$

$ (I - \gamma  P_\pi )V_{\pi} = R_{\pi} $

$ V_{\pi} = (I - \gamma  P_\pi )^{-1}R_{\pi} $

![示例图片](./GridWorld-状态转移矩阵.png)

In [4]:
# 状态转移矩阵
StateTransMat = np.zeros((2, 2))
for row in range(2):
    for col in range(2):
        StateTransMat[row, col] = np.dot(Prob_Action[row], Prob_State_by_Action[row, col])
print("状态转移矩阵：\n{0}".format(StateTransMat))

# 即时奖励向量
instant_rewards = np.zeros((2,1))
instant_rewards[0, 0] = np.dot(ActionReward[0], Prob_Action[0])
instant_rewards[1, 0] = np.dot(ActionReward[1], Prob_Action[1])
print('即时奖励：\n{0}'.format(instant_rewards))

I_2x2 = np.eye(2)
Inv_P = np.linalg.inv(I_2x2-Gamma*StateTransMat) # 求解逆矩阵
V_pi = np.matmul(Inv_P, instant_rewards)
print('V_pi:\n{0}'.format(V_pi))

状态转移矩阵：
[[0.66666667 0.33333333]
 [0.33333333 0.66666667]]
即时奖励：
[[ 0.        ]
 [-0.66666667]]
V_pi:
[[-2.85714286]
 [-3.80952381]]


### 2. 迭代方式求解状态价值向量的近似值

$ V^{k}_{\pi} = R_{\pi} + \gamma  P_{\pi} V^{k-1}_{\pi} ，\quad V_{\pi}是策略\pi下的状态价值向量，R_{\pi}是策略\pi下的即时奖励向量，\gamma是折扣因子，P_{\pi}是状态转移矩阵。$

In [12]:
# 状态价值。初始记录在第0行。
#StateValue = np.zeros((nEpoch+1, 2))
for itr in range(1, nEpoch + 1):
    V_k_1 = StateValue[itr-1].reshape(2,1)
    V_k = instant_rewards + np.matmul(Gamma*StateTransMat, V_k_1)
    StateValue[itr] = V_k.reshape((2,))
print(StateValue)

[[ 0.          0.        ]
 [ 0.         -0.66666667]
 [-0.2        -1.06666667]
 [-0.44       -1.36666667]
 [-0.674      -1.61866667]
 [-0.89       -1.84006667]
 [-1.08602    -2.03770667]
 [-1.262924   -2.21509667]
 [-1.4222834  -2.37460187]
 [-1.5657506  -2.51811281]
 [-1.6948842  -2.64725953]
 [-1.81110838 -2.76348765]
 [-1.91571132 -2.86809177]
 [-2.00985432 -2.96223512]
 [-2.09458313 -3.04696404]
 [-2.17083909 -3.12322003]
 [-2.23946946 -3.19185041]
 [-2.3012368  -3.25361775]
 [-2.35682741 -3.30920836]
 [-2.40685895 -3.3592399 ]
 [-2.45188734 -3.40426829]
 [-2.49241289 -3.44479385]
 [-2.52888589 -3.48126684]
 [-2.56171159 -3.51409254]
 [-2.59125471 -3.54363567]
 [-2.61784353 -3.57022448]
 [-2.64177346 -3.59415441]
 [-2.6633104  -3.61569135]
 [-2.68269365 -3.6350746 ]
 [-2.70013857 -3.65251952]
 [-2.715839   -3.66821995]
 [-2.72996938 -3.68235033]
 [-2.74268673 -3.69506768]
 [-2.75413234 -3.70651329]
 [-2.76443339 -3.71681435]
 [-2.77370434 -3.72608529]
 [-2.78204819 -3.73442914]
 

In [8]:
# 状态转移矩阵
Prob_State_to_State = np.zeros((2,2))

# 计算状态转移矩阵
for i in range(2):
    for j in range(2):
        Prob_State_to_State[i, j] = np.matmul(Prob_State_by_Action[i][j], Prob_Action[i].T)
print(Prob_State_to_State)

[[0.66666667 0.33333333]
 [0.33333333 0.66666667]]
